name: Build Electron App

on:
  push:
    tags:
      - "build*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "强制 Git 使用 HTTPS..."
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

          echo "清理 npm 缓存..."
          npm cache clean --force

          echo "尝试进行一次干净、详细的安装..."
          npm install --verbose --no-audit --legacy-peer-deps

      - name: Build application
        run: npm run make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: out/make/**/*
